### ISSUE TITLE
connect-standalone: command not found

### ISSUE THREAD

**Issue by lnpquang** [jcustenborder/kafka-connect-salesforce#21]
Dear,
I follow your instructions but i get error when run bin/debug.sh
The error message is:
connect-standalone: command not found

Please help on this!

Thanks.
Best regards,
LNPQuang

**Comment by jcustenborder** [comment]
You need to have `connect-standalone` in your path.  Take a look at this guide to [Installing and Configuring Kafka Connect](http://docs.confluent.io/current/connect/userguide.html)
