### ISSUE TITLE
kafka-connect-salesforce : /bin/connect-standalone: No such file or directory

### ISSUE THREAD

**Issue by krishna9191** [jcustenborder/kafka-connect-salesforce#25]
I am trying to run kafka-salesforce connector. I followed the steps mentioned on running the connector. But there is no **connect-standalone** file in the bin directory in the git repository itself. Even after the maven build, the connect-standalone file is not generated.  

the etc folder is also not there- neither in the repository nor after the building the project.

**Comment by jcustenborder** [comment]
@krishna9191 This is a connector that runs within a framework. This [documentation](https://docs.confluent.io/current/connect/index.html) might be helpful. Basically you need to take this connector and run it with kafka connect. You don't need to build it either as I supply releases through github.
