### ISSUE TITLE
Client does not auto subscribe to the push topic after a timeout

### ISSUE THREAD

**Issue by clari-akhilesh** [jcustenborder/kafka-connect-salesforce#5]
To reproduce, start the connector. Once the long polling starts, disconnect from network for a minute and reconnect. The is a successful handshake but the client does not automatically subscribe to the salesforce push topic.

**Comment by jcustenborder** [comment]
@clari-akhilesh I'm looking into this.

**Comment by jcustenborder** [comment]
@clari-akhilesh Can you try the latest version. I added a fix.

**Comment by jcustenborder** [comment]
Reconnection is fixed. Let me know if you have any issues.
