### ISSUE TITLE
How to give path and run these two command?

### ISSUE THREAD

**Issue by vivk89** [jcustenborder/kafka-connect-salesforce#6]
I have build packages but i am not understanding path and not able to run these.Could you please give some more information about these two?

export CLASSPATH="$(find target/ -type f -name '*.jar'| grep '\-package' | tr '\n' ':')"
$CONFLUENT_HOME/bin/connect-standalone $CONFLUENT_HOME/etc/schema-registry/connect-avro-standalone.properties config/MySourceConnector.properties

**Comment by jcustenborder** [comment]
You need to have kafka-connect available on your machine. Given I'm a Confluent employee, I use the [Confluent Platform](https://www.confluent.io/download/) for testing. On my environment I use $CONFLUENT_HOME as a pointer to where the platform is installed. This could be changed to just `connect-standalone` if `connect-standalone` is in the path.
